Repository bluesky-social/social-app, pull requests merged in 2024-01, with the labels that each got.

#2399 Do not nuke session on unknown backend errors
  package.json
  src/state/session/index.tsx
  yarn.lock
Labels: bugfix

#1732 Application Layout Framework
  src/App.web.tsx
  src/Navigation.tsx
  src/alf/README.md
  src/alf/atoms.ts
  src/alf/index.tsx
  src/alf/themes.ts
  src/alf/tokens.ts
  src/alf/types.ts
  src/alf/util/platform.ts
  src/alf/util/useColorModeTheme.ts
  src/view/com/Button.tsx
  src/view/com/Typography.tsx
  src/view/screens/DebugNew.tsx
Labels: improvement

#2385 Fix: Show setting header in web
  src/view/screens/Settings.tsx
Labels: x:changes-requested, improvement

#2419 add expandable context to composer when replying to post
  src/state/shell/composer.tsx
  src/view/com/composer/Composer.tsx
  src/view/com/composer/ComposerReplyTo.tsx
  src/view/com/post-thread/PostThreadItem.tsx
  src/view/com/post/Post.tsx
  src/view/com/posts/FeedItem.tsx
  src/view/screens/PostThread.tsx
Labels: improvement

#2356 Add Indonesian localization
  lingui.config.js
  src/locale/__tests__/helpers.test.ts
  src/locale/helpers.ts
  src/locale/i18n.ts
  src/locale/i18n.web.ts
  src/locale/languages.ts
  src/locale/locales/id/messages.po
Labels: intl

#2439 Update Ukrainian translations
  src/locale/locales/uk/messages.po
Labels: intl

#2436 Mark more texts for localization
  src/view/com/modals/ContentFilteringSettings.tsx
  src/view/com/modals/InviteCodes.tsx
  src/view/com/modals/UserAddRemoveLists.tsx
  src/view/screens/AppPasswords.tsx
  src/view/screens/Settings.tsx
Labels: intl

#2516 Update French localization with more strings
  src/locale/locales/fr/messages.po
Labels: intl

#2434 Adding catalan localization
  src/locale/locales/ca/messages.po
Labels: intl

#2126 New Web Layout
  bskyweb/templates/base.html
  package.json
  src/Navigation.tsx
  src/lib/batchedUpdates.web.ts
  src/lib/hooks/useWebBodyScrollLock.ts
  src/lib/hooks/useWebScrollRestoration.native.ts
  src/lib/hooks/useWebScrollRestoration.ts
  src/lib/styles.ts
  src/view/com/composer/text-input/web/EmojiPicker.web.tsx
  src/view/com/feeds/FeedPage.tsx
  src/view/com/lightbox/Lightbox.web.tsx
  src/view/com/modals/Modal.web.tsx
  src/view/com/pager/FeedsTabBar.web.tsx
  src/view/com/pager/FeedsTabBarMobile.tsx
  src/view/com/pager/Pager.tsx
  src/view/com/pager/Pager.web.tsx
  src/view/com/pager/PagerWithHeader.tsx
  src/view/com/pager/PagerWithHeader.web.tsx
  src/view/com/post-thread/PostThread.tsx
  src/view/com/util/List.tsx
  src/view/com/util/List.web.tsx
  src/view/com/util/MainScrollProvider.tsx
  src/view/com/util/SimpleViewHeader.tsx
  src/view/com/util/Toast.web.tsx
  src/view/com/util/fab/FABInner.tsx
  src/view/screens/PostThread.tsx
  src/view/screens/Search/Search.tsx
  src/view/shell/Composer.web.tsx
  src/view/shell/bottom-bar/BottomBarStyles.tsx
  src/view/shell/bottom-bar/BottomBarWeb.tsx
  src/view/shell/desktop/LeftNav.tsx
  src/view/shell/desktop/RightNav.tsx
  src/view/shell/index.web.tsx
  web/index.html
  yarn.lock
Labels: improvement

#2471 Update pt-BR translation
  src/locale/locales/pt-BR/messages.po
Labels: intl

#2509 Update Japanese localization based on the latest codebase
  src/locale/locales/ja/messages.po
Labels: intl

#2554 Update all missing translation for Indonesian languages.
  src/locale/locales/de/messages.po
  src/locale/locales/id/messages.po
Labels: intl, intl-needs-confirmation

#2494 Update Korean localization
  src/locale/locales/ko/messages.po
Labels: intl

#2427 Include expanded urls in social cards
  bskyweb/cmd/bskyweb/server.go
  bskyweb/templates/post.html
Labels: improvement

#2319 German translation updated
  src/locale/locales/de/messages.po
Labels: intl
