Repository bluesky-social/social-app, pull requests merged in 2024-04, with the labels that each got.

#3373 Separate ESLint and Prettier
  .eslintrc.js
  .github/workflows/lint.yml
  .gitignore
  .prettierignore
  package.json
Labels: bot: fingerprint changed

#3375 Use Prettier at the root
  .prettierignore
Labels: bot: fingerprint compatible

#3380 Remove unnecessary yarn call
  package.json
Labels: bot: fingerprint changed

#3387 Search - Make entire recent search clickable
  src/view/screens/Search/Search.tsx
Labels: bot: fingerprint compatible

#3372 Remove Button error boundary
  src/components/Button.tsx
Labels: bot: fingerprint compatible

#3102 Fabric migration - `rn-fetch-blob`, `react-native-fs` -> `expo-file-system`
  __tests__/lib/images.test.ts
  jest/jestSetup.js
  package.json
  src/lib/api/api-polyfill.ts
  src/lib/api/index.ts
  src/lib/media/manip.ts
  src/lib/media/picker.e2e.tsx
  src/view/com/modals/EditProfile.tsx
  src/view/com/util/Views.web.tsx
  src/view/com/util/forms/DateInput.tsx
  yarn.lock
Labels: bot: fingerprint changed

#2803 Update Indonesian ID translation to latest
  src/locale/locales/id/messages.po
Labels: intl, intl-needs-confirmation

#3329 Make notifications init reactive to queryClient
  src/App.native.tsx
  src/lib/notifications/notifications.ts
Labels: bot: fingerprint compatible

#3331 Factor QueryProvider out
  src/App.native.tsx
  src/App.web.tsx
  src/lib/react-query.tsx
Labels: bot: fingerprint compatible

#3391 run bundle/deploy on main pushes
  .github/workflows/bundle-deploy-eas-update.yml
Labels: bot: fingerprint compatible

#3392 don't fetch from origin if unnecessary when performing OTA deploy
  .github/workflows/bundle-deploy-eas-update.yml
Labels: bot: fingerprint compatible

#3394 Show redbox in DEV on string <View> child for web
  src/platform/polyfills.web.ts
Labels: bot: fingerprint compatible

#3395 Add cursor to 'learn more' on screenhider (close #2871)
  src/components/moderation/ScreenHider.tsx
Labels: bot: fingerprint compatible

#3396 Work around GitHub false-positive for passing secret to another action
  .github/workflows/build-submit-android.yml
  .github/workflows/bundle-deploy-eas-update.yml
Labels: bot: fingerprint compatible

#3090 Upgrade `UITextView` to latest
  modules/react-native-ui-text-view/README.md
  modules/react-native-ui-text-view/ios/RNUITextView-Bridging-Header.h
  modules/react-native-ui-text-view/ios/RNUITextView.swift
  modules/react-native-ui-text-view/ios/RNUITextViewChild.swift
  modules/react-native-ui-text-view/ios/RNUITextViewChildShadow.swift
  modules/react-native-ui-text-view/ios/RNUITextViewManager.m
  modules/react-native-ui-text-view/ios/RNUITextViewManager.swift
  modules/react-native-ui-text-view/ios/RNUITextViewShadow.swift
  modules/react-native-ui-text-view/package.json
  modules/react-native-ui-text-view/react-native-ui-text-view.podspec
  modules/react-native-ui-text-view/src/UITextView.tsx
  modules/react-native-ui-text-view/src/index.tsx
  package.json
  src/components/Typography.tsx
  src/view/com/util/text/Text.tsx
  yarn.lock
Labels: bot: fingerprint changed

#3333 Scope query client per DID
  src/App.native.tsx
  src/App.web.tsx
  src/lib/react-query.tsx
  src/state/session/index.tsx
Labels: bot: fingerprint compatible

#3327 Use ALF for the account quick switch dialog
  src/components/AccountList.tsx
  src/components/dialogs/BirthDateSettings.tsx
  src/components/dialogs/SwitchAccount.tsx
  src/screens/Login/ChooseAccountForm.tsx
  src/state/modals/index.tsx
  src/view/com/modals/Modal.tsx
  src/view/com/modals/SwitchAccount.tsx
  src/view/shell/bottom-bar/BottomBar.tsx
Labels: bot: fingerprint compatible

#3383 Add webpack analyzer, PR comments for webpack bundle size
  .github/workflows/pull-request-commit.yml
  .gitignore
  package.json
  webpack.config.js
  yarn.lock
Labels: bot: fingerprint changed

#3334 Simplify list logic further to prevent misuse
  .github/workflows/bundle-deploy-eas-update.yml
  .github/workflows/pull-request-commit.yml
  package.json
  src/components/Error.tsx
  src/components/LikedByList.tsx
  src/components/Lists.tsx
  src/lib/icons.tsx
  src/screens/Hashtag.tsx
  src/screens/Profile/ProfileLabelerLikedBy.tsx
  src/view/com/post-thread/PostThread.tsx
  src/view/com/profile/ProfileFollowers.tsx
  src/view/com/profile/ProfileFollows.tsx
Labels: bot: fingerprint changed

#3398 Lint against strings without wrapping <Text>
  .eslintrc.js
  eslint/__tests__/avoid-unwrapped-text.test.js
  eslint/avoid-unwrapped-text.js
  eslint/index.js
  package.json
  yarn.lock
Labels: bot: fingerprint changed

#3401 Fix profile follow from Likes
  src/state/queries/post-liked-by.ts
Labels: bot: fingerprint compatible

#3403 Don't mutate array
  src/state/queries/labeler.ts
Labels: bot: fingerprint compatible

#3402 rm 'pornography' label wording
  src/lib/moderation/useGlobalLabelStrings.ts
  src/lib/moderation/useReportOptions.ts
Labels: bot: fingerprint compatible

#3317 Open share sheet when long pressing link
  src/components/Link.tsx
  src/components/RichText.tsx
  src/lib/sharing.ts
  src/state/modals/index.tsx
  src/view/com/modals/LinkWarning.tsx
Labels: bot: fingerprint compatible

#3397 Enable tags on profile descriptions (close #3081)
  src/screens/Profile/Header/ProfileHeaderLabeler.tsx
  src/screens/Profile/Header/ProfileHeaderStandard.tsx
Labels: bot: fingerprint compatible

#3404 Extract query key roots to constants
  src/lib/react-query.tsx
  src/state/queries/actor-autocomplete.ts
  src/state/queries/actor-search.ts
  src/state/queries/app-passwords.ts
  src/state/queries/feed.ts
  src/state/queries/handle.ts
  src/state/queries/invites.ts
  src/state/queries/labeler.ts
  src/state/queries/list-members.ts
  src/state/queries/list-memberships.ts
  src/state/queries/list.ts
  src/state/queries/my-blocked-accounts.ts
  src/state/queries/my-follows.ts
  src/state/queries/my-lists.ts
  src/state/queries/my-muted-accounts.ts
  src/state/queries/notifications/feed.ts
  src/state/queries/post-feed.ts
  src/state/queries/post-reposted-by.ts
  src/state/queries/post-thread.ts
  src/state/queries/post.ts
  src/state/queries/preferences/index.ts
  src/state/queries/profile-feedgens.ts
  src/state/queries/profile-followers.ts
  src/state/queries/profile-follows.ts
  src/state/queries/profile-lists.ts
  src/state/queries/profile.ts
  src/state/queries/resolve-uri.ts
  src/state/queries/search-posts.ts
  src/state/queries/service.ts
  src/state/queries/suggested-feeds.ts
  src/state/queries/suggested-follows.ts
Labels: bot: fingerprint changed

#3405 replace deprecated `term` with `q` in search actor
  src/state/queries/actor-autocomplete.ts
  src/state/queries/actor-search.ts
Labels: bot: fingerprint compatible

#3407 Enforce Text suffix for Text-rendering components
  .eslintrc.js
  eslint/__tests__/avoid-unwrapped-text.test.js
  eslint/avoid-unwrapped-text.js
  src/components/Link.tsx
  src/components/Prompt.tsx
  src/components/RichText.tsx
  src/components/dialogs/MutedWords.tsx
  src/components/forms/DateField/index.android.tsx
  src/components/forms/DateField/index.tsx
  src/components/forms/DateField/index.web.tsx
  src/components/forms/TextField.tsx
  src/components/forms/Toggle.tsx
  src/components/moderation/LabelPreference.tsx
  src/components/moderation/LabelsOnMeDialog.tsx
  src/components/moderation/ModerationDetailsDialog.tsx
  src/screens/Login/ChooseAccountForm.tsx
  src/screens/Login/ForgotPasswordForm.tsx
  src/screens/Login/FormContainer.tsx
  src/screens/Login/LoginForm.tsx
  src/screens/Login/SetNewPasswordForm.tsx
  src/screens/Moderation/index.tsx
  src/screens/Onboarding/Layout.tsx
  src/screens/Onboarding/StepAlgoFeeds/index.tsx
  src/screens/Onboarding/StepFinished.tsx
  src/screens/Onboarding/StepFollowingFeed.tsx
  src/screens/Onboarding/StepInterests/index.tsx
  src/screens/Onboarding/StepModeration/AdultContentEnabledPref.tsx
  src/screens/Onboarding/StepModeration/index.tsx
  src/screens/Onboarding/StepSuggestedAccounts/index.tsx
  src/screens/Onboarding/StepTopicalFeeds.tsx
  src/screens/Profile/Header/Metrics.tsx
  src/screens/Profile/Header/ProfileHeaderLabeler.tsx
  src/screens/Signup/StepInfo/Policies.tsx
  src/screens/Signup/StepInfo/index.tsx
  src/screens/Signup/index.tsx
  src/view/com/auth/SplashScreen.web.tsx
  src/view/com/auth/server-input/index.tsx
  src/view/screens/DebugMod.tsx
  src/view/screens/ProfileFeed.tsx
  src/view/screens/Settings/ExportCarDialog.tsx
  src/view/screens/Storybook/Dialogs.tsx
  src/view/screens/Storybook/Forms.tsx
  src/view/screens/Storybook/Links.tsx
Labels: bot: fingerprint compatible

#3406 fix comments on prs
  .github/workflows/pull-request-commit.yml
Labels: bot: fingerprint compatible

#3436 Bump `async-storage` to comply with App Store guidelines
  package.json
  yarn.lock
Labels: missing-api-declarations

#3336 Use ALF for the embed consent modal
  src/components/dialogs/EmbedConsent.tsx
  src/state/modals/index.tsx
  src/view/com/modals/EmbedConsent.tsx
  src/view/com/modals/Modal.tsx
  src/view/com/modals/Modal.web.tsx
  src/view/com/util/post-embeds/ExternalGifEmbed.tsx
  src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx
Labels: bot: fingerprint compatible

#3388 Italian Localization
  src/locale/locales/it/messages.po
Labels: intl, intl-needs-confirmation

#3385 [iPad support] Custom tab navigator for native tablet, with side nav
  src/Navigation.tsx
  src/components/Prompt.tsx
  src/lib/hooks/useNavigationTabState.ts
  src/lib/routes/types.ts
  src/view/com/composer/Composer.tsx
  src/view/com/feeds/FeedPage.tsx
  src/view/com/home/HomeHeaderLayoutMobile.tsx
  src/view/com/profile/ProfileSubpageHeader.tsx
  src/view/com/util/SimpleViewHeader.tsx
  src/view/com/util/fab/FAB.web.tsx
  src/view/com/util/fab/FABInner.tsx
  src/view/com/util/layouts/TitleColumnLayout.tsx
  src/view/com/util/load-latest/LoadLatestBtn.tsx
  src/view/screens/Search/Search.tsx
  src/view/shell/createNativeStackNavigatorWithAuth.tsx
  src/view/shell/desktop/LeftNav.tsx
  src/view/shell/desktop/RightNav.tsx
  src/view/shell/index.tsx
Labels: bot: fingerprint changed

#3408 Search - extra tabs
  src/lib/statsig/gates.ts
  src/state/queries/search-posts.ts
  src/view/screens/Search/Search.tsx
Labels: bot: fingerprint compatible

#3537 Update Ukrainian translation
  src/locale/locales/uk/messages.po
Labels: intl, intl-needs-confirmation

#3623 [GIFs] Fix infinite pagination issue by forcing flatlist to scroll
  src/components/Dialog/index.web.tsx
  src/components/dialogs/GifSelect.tsx
Labels: bugfix
